import type { RuneNode } from '../types'

export const RUNE_NODES: RuneNode[] = [
  // Exploración
  {
    id: 'exp_1',
    group: 'exploracion',
    x: 80,
    y: 60,
    cost: 20,
    prereqs: [],
    grants: { expBonus: 5 },
    nameKey: 'Sendero',
    descKey: '+5% experiencia',
  },
  {
    id: 'exp_2',
    group: 'exploracion',
    x: 160,
    y: 40,
    cost: 40,
    prereqs: ['exp_1'],
    grants: { expBonus: 8 },
    nameKey: 'Mapa',
    descKey: '+8% experiencia',
  },
  {
    id: 'exp_3',
    group: 'exploracion',
    x: 240,
    y: 70,
    cost: 80,
    prereqs: ['exp_2'],
    grants: { goldFind: 10 },
    nameKey: 'Caravana',
    descKey: '+10% oro',
  },
  {
    id: 'exp_4',
    group: 'exploracion',
    x: 320,
    y: 50,
    cost: 150,
    prereqs: ['exp_3'],
    grants: { heroSlots: 1 },
    nameKey: 'Campamento',
    descKey: '+1 hueco de héroe',
  },
  {
    id: 'exp_5',
    group: 'exploracion',
    x: 400,
    y: 80,
    cost: 300,
    prereqs: ['exp_4'],
    grants: { expBonus: 15, goldFind: 10 },
    nameKey: 'Horizonte',
    descKey: '+15% EXP, +10% oro',
  },
  // Combate
  {
    id: 'cmb_1',
    group: 'combate',
    x: 80,
    y: 180,
    cost: 25,
    prereqs: [],
    grants: { increasedDamage: 5 },
    nameKey: 'Filo',
    descKey: '+5% daño',
  },
  {
    id: 'cmb_2',
    group: 'combate',
    x: 160,
    y: 200,
    cost: 50,
    prereqs: ['cmb_1'],
    grants: { attackSpeed: 5 },
    nameKey: 'Ritmo',
    descKey: '+5% velocidad de ataque',
  },
  {
    id: 'cmb_3',
    group: 'combate',
    x: 240,
    y: 170,
    cost: 90,
    prereqs: ['cmb_2'],
    grants: { critChance: 4 },
    nameKey: 'Punto Vital',
    descKey: '+4% crítico',
  },
  {
    id: 'cmb_4',
    group: 'combate',
    x: 320,
    y: 210,
    cost: 160,
    prereqs: ['cmb_3'],
    grants: { critDamage: 20 },
    nameKey: 'Desgarro',
    descKey: '+20% daño crítico',
  },
  {
    id: 'cmb_5',
    group: 'combate',
    x: 400,
    y: 180,
    cost: 320,
    prereqs: ['cmb_4'],
    grants: { increasedDamage: 15, armor: 20 },
    nameKey: 'Muro de Acero',
    descKey: '+15% daño, +20 armadura',
  },
  {
    id: 'cmb_6',
    group: 'combate',
    x: 200,
    y: 250,
    cost: 120,
    prereqs: ['cmb_2'],
    grants: { maxHp: 40 },
    nameKey: 'Vitalidad',
    descKey: '+40 vida',
  },
  // Botín
  {
    id: 'bot_1',
    group: 'botin',
    x: 80,
    y: 320,
    cost: 30,
    prereqs: [],
    grants: { magicFind: 8 },
    nameKey: 'Ojo Avido',
    descKey: '+8% hallazgo mágico',
  },
  {
    id: 'bot_2',
    group: 'botin',
    x: 160,
    y: 300,
    cost: 60,
    prereqs: ['bot_1'],
    grants: { goldFind: 12 },
    nameKey: 'Bolsa',
    descKey: '+12% oro',
  },
  {
    id: 'bot_3',
    group: 'botin',
    x: 240,
    y: 340,
    cost: 110,
    prereqs: ['bot_2'],
    grants: { magicFind: 12 },
    nameKey: 'Criba',
    descKey: '+12% hallazgo mágico',
  },
  {
    id: 'bot_4',
    group: 'botin',
    x: 320,
    y: 310,
    cost: 200,
    prereqs: ['bot_3'],
    grants: { magicFind: 20, goldFind: 15 },
    nameKey: 'Tesoro',
    descKey: '+20% MF, +15% oro',
  },
  {
    id: 'bot_5',
    group: 'botin',
    x: 400,
    y: 350,
    cost: 400,
    prereqs: ['bot_4'],
    grants: { magicFind: 30 },
    nameKey: 'Cornucopia',
    descKey: '+30% hallazgo mágico',
  },
  // Oficio
  {
    id: 'ofi_1',
    group: 'oficio',
    x: 80,
    y: 440,
    cost: 35,
    prereqs: [],
    grants: { hpRegen: 1 },
    nameKey: 'Taller',
    descKey: '+1 regeneración',
  },
  {
    id: 'ofi_2',
    group: 'oficio',
    x: 160,
    y: 460,
    cost: 70,
    prereqs: ['ofi_1'],
    grants: { armor: 15 },
    nameKey: 'Forja',
    descKey: '+15 armadura',
  },
  {
    id: 'ofi_3',
    group: 'oficio',
    x: 240,
    y: 430,
    cost: 130,
    prereqs: ['ofi_2'],
    grants: { flatFire: 3, flatIce: 3 },
    nameKey: 'Alquimia',
    descKey: '+3 fuego y hielo',
  },
  {
    id: 'ofi_4',
    group: 'oficio',
    x: 320,
    y: 470,
    cost: 250,
    prereqs: ['ofi_3'],
    grants: { heroSlots: 1 },
    nameKey: 'Gremio',
    descKey: '+1 hueco de héroe',
  },
  {
    id: 'ofi_5',
    group: 'oficio',
    x: 400,
    y: 440,
    cost: 450,
    prereqs: ['ofi_4'],
    grants: { increasedDamage: 10, maxHp: 60, magicFind: 10 },
    nameKey: 'Maestría',
    descKey: '+10% daño, +60 HP, +10% MF',
  },
]

export const RUNE_BY_ID = Object.fromEntries(
  RUNE_NODES.map((n) => [n.id, n]),
) as Record<string, RuneNode>
