export const strings = {
  gameTitle: 'Ganar: Crónica Ociosa',
  gold: 'Oro',
  settings: 'Ajustes',
  heroes: 'Héroes',
  inventory: 'Inventario',
  stash: 'Almacén',
  cube: 'Cubo',
  runes: 'Runas',
  achievements: 'Logros',
  shop: 'Tienda',
  close: 'Cerrar',
  resume: 'Reanudar',
  frozenTitle: 'Simulación en pausa',
  frozenBody:
    'La pestaña estuvo demasiado tiempo en segundo plano. Reanudá para aplicar el progreso con seguridad.',
  offlineTitle: 'Informe de ausencia',
  offlineBody: 'Mientras no estabas, tu partida siguió su curso.',
  offlineKills: 'Derrotas',
  offlineGold: 'Oro ganado',
  offlineExp: 'Experiencia',
  offlineItems: 'Botín destacado',
  claim: 'Reclamar',
  equip: 'Equipar',
  unequip: 'Desequipar',
  sell: 'Vender',
  emptySlot: 'Vacío',
  level: 'Nivel',
  stage: 'Etapa',
  act: 'Acto',
  wave: 'Oleada',
  difficulty: 'Dificultad',
  exportSave: 'Exportar partida',
  importSave: 'Importar partida',
  resetSave: 'Borrar partida',
  speed: 'Velocidad',
  sound: 'Sonido',
  pixelScale: 'Escala de píxel',
  stashInCube: 'Incluir almacén en el Cubo',
  backToSite: '← Manuscrito',
  buyHeroSlot: 'Comprar hueco de héroe',
  hireHero: 'Contratar',
  noItems: 'Sin objetos',
  cubeFill: 'Autorrelleno',
  cubeCraft: 'Sintetizar',
  cubeModeSynth: 'Síntesis (9 → 1)',
  cubeModeAdd: 'Añadir estadística',
  cubeModeReroll: 'Relanzar afijos',
  runeBuy: 'Desbloquear',
  runeRefund: 'Reembolsar última',
  innate: 'Características innatas',
  requiresClass: 'Clase',
  requiresLevel: 'Nivel requerido',
  value: 'Valor',
  damage: 'Daño',
  armor: 'Armadura',
  aps: 'Ataques/s',
  hp: 'Vida',
  crit: 'Crítico',
  partyDps: 'DPS del grupo',
  unlocked: 'Desbloqueado',
  locked: 'Bloqueado',
  reward: 'Recompensa',
  common: 'Común',
  uncommon: 'Poco común',
  rare: 'Rara',
  legendary: 'Legendaria',
  immortal: 'Inmortal',
  arcane: 'Arcana',
  beyond: 'Más allá',
  celestial: 'Celestial',
  divine: 'Divina',
  cosmic: 'Cósmica',
  diff_vencer: 'Vencer',
  diff_conquistar: 'Conquistar',
  diff_merecer: 'Merecer',
  diff_triunfar: 'Triunfar',
  class_guerrero: 'Guerrero',
  class_arquero: 'Arquero',
  class_mago: 'Mago',
  class_picaro: 'Pícaro',
  class_clerigo: 'Clérigo',
  class_barbaro: 'Bárbaro',
  class_ballestero: 'Ballestero',
  skill_guerrero: 'Embate',
  skill_arquero: 'Lluvia de flechas',
  skill_mago: 'Orbe arcano',
  skill_picaro: 'Puñalada',
  skill_clerigo: 'Fulgor sagrado',
  skill_barbaro: 'Furia',
  skill_ballestero: 'Saeta perforante',
  shopHint: 'Oro por mejoras rápidas y huecos de héroe.',
  buyHeal: 'Poción de grupo (cura)',
  buyExp: 'Tomo de experiencia',
  panelHeroes: 'Héroes',
  panelInv: 'Botín',
  panelCube: 'Cubo',
  panelRunes: 'Runas',
  panelAch: 'Logros',
  panelShop: 'Tienda',
  panelSettings: 'Ajustes',
} as const

export type StringKey = keyof typeof strings

export function t(key: StringKey): string {
  return strings[key]
}
